name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest #idealmente fixar essa versao dps

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest black ruff

    - name: Lint with ruff
      run: |
        ruff check task_py
    - name: Check formatting with black
      run: |
        black --check task_py

    - name: Run tests
      run: |
        pytest tests || echo "No tests yet"

